{
    "status": 200,
    "data": {
        "pageNum": 1,
        "page_size": 10,
        "size": 10,
        "orderBy": "core DESC",
        "startRow": 0,
        "endRow": 9,
        "total": 50,
        "pages": 5,
        "firstPage": 1,
        "prePage": 0,
        "nextPage": 2,
        "lastPage": 5,
        "isfirstPage": true,
        "islastPage": false,
        "hasPreviousPage": false,
        "hasNextPage": true,
        "navigatePages": 5,
        "navigatepageNums": "[1, 2, 3, 4, 5]",
        "list": [
            {
                "id": 10001,
                "coverimg": "https://example.com/cover.jpg",
                "videotime": "180",
                "playnum": 500,
                "userid": 100001,
                "tag": "知识科普",
                "recommengstr": "轻松有趣",
                "type": 1,
                "introduce": "生动有趣的数学启蒙视频，让孩子轻松爱上数学",
                "createtime": "06-21",
                "username": "小明老师",
                "userheadurl": "https://example.com/10001",
                "userisvertify": true,
                "zannum": 180,
                "videourl": "https://example.com/child_education_video.mp4",
                "userfancount": 800,
                "userdesc": "专注于为小朋友提供优质教育内容"
            },
            {
                "id": 10002,
                "coverimg": "https://www.fo9c.cn/multimedia/10002.jpg",
                "videotime": "1090",
                "playnum": 3522,
                "userid": 100002,
                "tag": "数学",
                "recommengstr": "知识课堂",
                "type": 1,
                "introduce": "能读懂学生内心的数学课堂",
                "createtime": "12-03",
                "username": "微课资料站",
                "userheadurl": "https://example.com/10002",
                "userisvertify": true,
                "zannum": 561,
                "videourl": "https://example.com/child_education_video.mp4",
                "userfancount": 10235,
                "userdesc": "10002"
            },
            {
                "id": 10003,
                "coverimg": "https://www.fo9c.cn/multimedia/10003.jpg",
                "videotime": "2310",
                "playnum": 4344,
                "userid": 100003,
                "tag": "趣味文字",
                "recommengstr": "教学设计",
                "type": 2,
                "introduce": "大三师范专业教学设计课程",
                "createtime": "10-11",
                "username": "王亢奋",
                "userheadurl": "https://example.com/10003",
                "userisvertify": true,
                "zannum": 561,
                "videourl": "https://example.com/child_education_video.mp4",
                "userfancount": 10235,
                "userdesc": "10003"
            },
            {
                "id": 10004,
                "coverimg": "https://www.fo9c.cn/multimedia/10004.jpg",
                "videotime": "2310",
                "playnum": 16420,
                "userid": 100004,
                "tag": "课堂游戏",
                "recommengstr": "课堂游戏",
                "type": 2,
                "introduce": "\r\n小学注意力课堂游戏《眼力弹弹弹》",
                "createtime": "04-23",
                "username": "明明是老师_",
                "userheadurl": "https://example.com/10004",
                "userisvertify": true,
                "zannum": 561,
                "videourl": "https://example.com/child_education_video.mp4",
                "userfancount": 10235,
                "userdesc": "10003"
            },
            {
                "id": 10005,
                "coverimg": "https://www.fo9c.cn/multimedia/10005.jpg",
                "videotime": "6845",
                "playnum": 6841,
                "userid": 100005,
                "tag": "作文",
                "recommengstr": "神笔作文",
                "type": 3,
                "introduce": "神笔作文趣味课堂 小学2-6年级写作课",
                "createtime": "03-30",
                "username": "dc008",
                "userheadurl": "https://example.com/10005",
                "userisvertify": true,
                "zannum": 0,
                "videourl": null,
                "userfancount": 0,
                "userdesc": null
            },
            {
                "id": 10006,
                "coverimg": "https://www.fo9c.cn/multimedia/10006.jpg",
                "videotime": "49320",
                "playnum": 6310,
                "userid": 100006,
                "tag": null,
                "recommengstr": "自然科普",
                "type": 2,
                "introduce": "不走弯路的小学生自然科普启蒙，9大主题，开启探索科学之旅。",
                "createtime": "03-10",
                "username": "魔法学院molly100623",
                "userheadurl": null,
                "userisvertify": false,
                "zannum": 0,
                "videourl": null,
                "userfancount": 0,
                "userdesc": null
            },
            {
                "id": 10007,
                "coverimg": "https://www.fo9c.cn/multimedia/10007.jpg",
                "videotime": "16520",
                "playnum": 4921,
                "userid": 100007,
                "tag": null,
                "recommengstr": "趣味实验",
                "type": 1,
                "introduce": "【趣味课堂】云支教第一季——科学实验合集",
                "createtime": "06-15",
                "username": "华理药科协会",
                "userheadurl": null,
                "userisvertify": false,
                "zannum": 0,
                "videourl": null,
                "userfancount": 0,
                "userdesc": null
            },
            {
                "id": 10008,
                "coverimg": "https://www.fo9c.cn/multimedia/10008.jpg",
                "videotime": "2650",
                "playnum": 763,
                "userid": 100008,
                "tag": null,
                "recommengstr": "建议收藏",
                "type": 3,
                "introduce": "好玩有趣的六一班级特色活动，小朋友们太爱了！",
                "createtime": "01-12",
                "username": "晴天老师在成长",
                "userheadurl": null,
                "userisvertify": false,
                "zannum": 0,
                "videourl": null,
                "userfancount": 0,
                "userdesc": null
            }
        ]
    }
}
